language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install tox-travis codecov flake8

script:
  - tox
  - flake8 hashedindex test
after_success:
  - codecov
cache: pip
