language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install tox-travis codecov flake8 restructuredtext_lint

script:
  - tox
  - flake8 hashedindex test
  - rst-lint *.rst

after_success:
  - codecov
cache: pip
